language: r

dist: trusty

warnings_are_errors: false
sudo: required

apt_packages:
  - libv8-dev

r_packages:
  - rstudioapi
  - stringr
  - shiny

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'

